artifact creation and error logs added in deploy static portal workflow

diff --git a/.github/workflows/DeployStaticPortal.yml b/.github/workflows/DeployStaticPortal.yml
--- a/.github/workflows/DeployStaticPortal.yml
+++ b/.github/workflows/DeployStaticPortal.yml
@@ -19,20 +19,31 @@ jobs:
     - name: Zip files
       run: zip -qq -r portal-input.zip .
       
+    # Call Apimatic Endpoint to generate Portal
     - name: Call build endpoint
-      run: curl -X POST --url 'https://www.apimatic.io/api/portal' -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}' -F 'file=@portal-input.zip' -o portal-output.zip
-      
+      id: generate-portal
+      run: | 
+        RESPONSE=`curl -s --write-out '%{http_code}\t%{content_type}' --request POST --url 'https://www.apimatic.io/api/portal' \
+          -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}' -F 'file=@portal-input.zip' -OJ`;
+        
+        HTTP_CODE=$(echo $RESPONSE | cut -d " " -f 1);
+        CONTENT_TYPE=$(echo $RESPONSE | cut -d " " -f 2);
+        echo "HTTP_CODE=$HTTP_CODE" >> $GITHUB_OUTPUT;
+        echo "CONTENT_TYPE=$CONTENT_TYPE" >> $GITHUB_OUTPUT;
+
     - name: list 
       run: ls
       
     - name: Extract generated Portal
-      run: unzip -qq portal-output.zip -d static-portal
+      if: ${{steps.generate-portal.outputs.HTTP_CODE == '200'}}
+      run: unzip -qq portal.zip -d static-portal
       
     - name: list 
       run: ls
       
 
     - name: Deploy to Netlify
+      if: ${{steps.generate-portal.outputs.HTTP_CODE == '200'}}
       uses: nwtgck/actions-netlify@v1.2
       with:
         publish-dir: './static-portal'
@@ -46,5 +57,40 @@ jobs:
         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
       timeout-minutes: 1
+
+      # Upload Portal Artifact
+    - name: Upload Artifact
+      if: ${{steps.generate-portal.outputs.HTTP_CODE == '200' }}
+      uses: actions/upload-artifact@v3.1.1
+      with:
+        name: static-portal
+        path: static-portal
+
+    # Unzip error file if error code is 422 with a zip file
+    - name: Unzip error file
+      if: ${{steps.generate-portal.outputs.HTTP_CODE == '422' && steps.generate-portal.outputs.CONTENT_TYPE == 'application/zip'}}
+      run: unzip -qq error.zip -d error
+      
+    # Upload error.zip if error code is 422 with a zip file
+    - name: Upload error.zip
+      if: ${{steps.generate-portal.outputs.HTTP_CODE == '422' && steps.generate-portal.outputs.CONTENT_TYPE == 'application/zip'}}
+      uses: actions/upload-artifact@v3.1.1
+      with:
+        name: error
+        path: error
+
+    # Fail job if API response is not 200
+    - name: Log error if not successful
+      if: ${{steps.generate-portal.outputs.HTTP_CODE != '200' && steps.generate-portal.outputs.CONTENT_TYPE != 'application/zip'}}
+      run: |
+        echo "The Portal Generation request failed with response code ${{steps.generate-portal.outputs.HTTP_CODE}} and message $(cat portal)"; \
+        exit 1
+        
+    # Fail job if API response is not 200 and is a zip file
+    - name: Log error if not successful
+      if: ${{steps.generate-portal.outputs.HTTP_CODE != '200' && steps.generate-portal.outputs.CONTENT_TYPE == 'application/zip'}}
+      run: |
+        echo "The Portal Generation request failed with response code ${{steps.generate-portal.outputs.HTTP_CODE}}; \
+        exit 1
     
       
